var Settings = {
  TILE_SIZE: 48,
  ROOM_HEIGHT_IN_TILE: 6,
  INVENTORY_WIDTH_IN_TILES_MOBILE: 1.25,
  INVENTORY_WIDTH_IN_TILES_DESKTOP: 0,
  INVENTORY_HEIGHT_IN_TILES_MOBILE: 0,
  INVENTORY_HEIGHT_IN_TILES_DESKTOP: 1,
  ROOM_FRAME_IN_TILES_DESKTOP: 0.5,
  ROOM_FRAME_IN_TILES_MOBILE: 0.25,
  SCREEN_PROPS: {
    // Dinamiche, temporaneo!!
    calculatedWidth: 683,
    calculatedHeight: 384
  },
  DEVICE: ''
};

module.exports = Settings;
