const CONST = {
  EXAMINABLE: 'EXAMINABLE',
  INERT: 'INERT',
  INTERACTIVE: 'INTERACTIVE',
  TALKABLE: 'TALKABLE',
  INVENTORY: 'INVENTORY',

  DEFAULT_MIN_LIGHT_LEVEL_TO_OBSERVE: 0.05,
  DEFAULT_OBSERVE_TEXT: 'Observe default text',
  DEFAULT_NO_LIGHT_OBSERVE_TEXT: 'NoLightObserve default text',
  DEFAULT_MIN_LIGHT_LEVEL_TO_EXAMINE_OR_INTERACT: 0.04,
  DEFAULT_EXAMINE_OR_INTERACT_TEXT: 'ExamineOrInteract default text',
  DEFAULT_NO_LIGHT_EXAMINE_OR_INTERACT_TEXT: 'NoLightExamineOrInteract default text'
};

module.exports = CONST;
